import type { Tool } from "@/types";

export const TOOLS: Tool[] = [
  {
    id: "json",
    name: "Formatador JSON",
    description: "Formate, valide, minifique e converta JSON para TypeScript",
    category: "JSON",
    href: "/tools/json",
    icon: "Braces",
    tags: ["json", "formatar", "validar", "typescript"],
    hasAI: true,
  },
  {
    id: "jsonpath",
    name: "JSONPath",
    description: "Filtre JSON com expressões JSONPath (no browser)",
    category: "JSON",
    href: "/tools/jsonpath",
    icon: "Filter",
    tags: ["jsonpath", "json", "query", "filtrar"],
    isNew: true,
    addedAt: "2026-05-15",
  },
  {
    id: "yaml",
    name: "YAML ↔ JSON",
    description: "Converta entre YAML e JSON para Kubernetes, CI/CD e configs",
    category: "JSON",
    href: "/tools/yaml",
    icon: "FileCode2",
    tags: ["yaml", "json", "kubernetes", "config", "converter"],
    isNew: true,
  },
  {
    id: "regex",
    name: "Testador de Regex",
    description: "Teste expressões regulares com highlighting e explicação por IA",
    category: "Text",
    href: "/tools/regex",
    icon: "Regex",
    tags: ["regex", "regexp", "padrão", "expressão regular"],
    hasAI: true,
  },
  {
    id: "base64",
    name: "Codificador Base64",
    description: "Codifique e decodifique Base64, URL e entidades HTML",
    category: "Encoding",
    href: "/tools/base64",
    icon: "Binary",
    tags: ["base64", "codificar", "decodificar", "url", "html"],
  },
  {
    id: "jwt",
    name: "JWT — decodificar e gerar",
    description: "Decodifique tokens ou gere JWT HS256 para testes locais",
    category: "Security",
    href: "/tools/jwt",
    icon: "KeyRound",
    tags: ["jwt", "token", "auth", "decodificar", "hs256"],
  },
  {
    id: "pem",
    name: "Visualizador PEM / certificado",
    description: "Cole PEM de certificado X.509 e veja subject, validade e fingerprints",
    category: "Security",
    href: "/tools/pem",
    icon: "FileKey",
    tags: ["pem", "x509", "certificado", "ssl", "tls"],
    isNew: true,
    addedAt: "2026-05-15",
  },
  {
    id: "secrets",
    name: "Gerador de Secrets",
    description: "Gere secrets aleatórios em base64 ou hex (openssl rand)",
    category: "Security",
    href: "/tools/secrets",
    icon: "Key",
    tags: ["secret", "openssl", "jwt", "webhook", "base64", "hex", "random"],
    isNew: true,
  },
  {
    id: "hash",
    name: "Gerador de Hash",
    description: "Digest MD5/SHA-2, HMAC para webhooks e comparação de hashes",
    category: "Security",
    href: "/tools/hash",
    icon: "Hash",
    tags: ["hash", "sha256", "sha384", "sha3", "blake2", "hmac", "md5", "webhook", "criptografia"],
  },
  {
    id: "estampas",
    name: "Estúdio de Estampas",
    description:
      "Prepare arte para camisetas: remover fundo (Rembg), DPI, knockout, presets DTF e camisa preta, export PNG/WebP",
    category: "Images",
    href: "/tools/estampas",
    icon: "Shirt",
    tags: ["estampa", "camiseta", "dtf", "sublimação", "knockout", "imagem", "rembg", "sharp"],
    isNew: true,
  },
  {
    id: "imagem-dev",
    name: "Imagem para dev",
    description: "Remova metadados EXIF e descarregue pack de favicons PNG (ZIP)",
    category: "Images",
    href: "/tools/imagem-dev",
    icon: "ImageDown",
    tags: ["imagem", "exif", "favicon", "png", "zip"],
    isNew: true,
    addedAt: "2026-05-15",
  },
  {
    id: "colors",
    name: "Conversor de Cores",
    description: "Converta entre HEX, RGB, HSL, HSV e CMYK com preview",
    category: "Colors",
    href: "/tools/colors",
    icon: "Palette",
    tags: ["cor", "hex", "rgb", "hsl", "css"],
  },
  {
    id: "password",
    name: "Gerador de Senha",
    description: "Gere senhas seguras com regras customizáveis e análise de força",
    category: "Security",
    href: "/tools/password",
    icon: "ShieldCheck",
    tags: ["senha", "segurança", "gerador", "aleatório"],
  },
  {
    id: "uuid",
    name: "Gerador de UUID",
    description: "Gere UUIDs v4 criptograficamente seguros em massa",
    category: "Utilities",
    href: "/tools/uuid",
    icon: "Fingerprint",
    tags: ["uuid", "guid", "id", "único"],
  },
  {
    id: "diff",
    name: "Comparador de Texto",
    description: "Compare dois textos e visualize as diferenças com highlighting",
    category: "Text",
    href: "/tools/diff",
    icon: "GitCompare",
    tags: ["diff", "comparar", "texto", "diferenças"],
  },
  {
    id: "markdown",
    name: "Preview Markdown",
    description: "Escreva Markdown e veja o preview renderizado em tempo real",
    category: "Text",
    href: "/tools/markdown",
    icon: "FileText",
    tags: ["markdown", "md", "preview", "renderizar"],
  },
  {
    id: "lorem",
    name: "Lorem & dados fictícios",
    description: "Gere texto e dados de teste com seed reproduzível (Faker)",
    category: "Text",
    href: "/tools/lorem",
    icon: "Library",
    tags: ["lorem", "faker", "dados", "teste", "seed"],
    isNew: true,
    addedAt: "2026-05-15",
  },
  {
    id: "code-review",
    name: "Revisão de Código IA",
    description: "Revise seu código com IA: bugs, performance e boas práticas",
    category: "Code",
    href: "/tools/code-review",
    icon: "Bot",
    tags: ["ia", "código", "revisão", "refatorar"],
    hasAI: true,
  },
  {
    id: "sql",
    name: "Formatador SQL",
    description: "Formate queries SQL e obtenha explicações por IA",
    category: "Database",
    href: "/tools/sql",
    icon: "Database",
    tags: ["sql", "banco de dados", "query", "formatar"],
    hasAI: true,
  },
  {
    id: "env",
    name: "Formatador .env",
    description: "Valide, ordene e mascare variáveis de ambiente",
    category: "Utilities",
    href: "/tools/env",
    icon: "Variable",
    tags: ["env", "dotenv", "variáveis", "ambiente", "secrets"],
    isNew: true,
  },
  {
    id: "base-converter",
    name: "Conversor de bases",
    description: "Converta entre binário, octal, decimal e hexadecimal",
    category: "Utilities",
    href: "/tools/base-converter",
    icon: "Calculator",
    tags: ["binário", "hex", "decimal", "octal", "base", "número"],
    isNew: true,
  },
  {
    id: "cron",
    name: "Interpretador Cron",
    description: "Interprete e gere expressões cron com descrição em português",
    category: "Utilities",
    href: "/tools/cron",
    icon: "Clock",
    tags: ["cron", "agendamento", "tempo", "job"],
  },
  {
    id: "timestamp",
    name: "Conversor de Timestamp",
    description: "Converta timestamps Unix para datas legíveis e vice-versa",
    category: "Utilities",
    href: "/tools/timestamp",
    icon: "Timer",
    tags: ["timestamp", "unix", "data", "tempo", "converter"],
  },
  {
    id: "mime",
    name: "MIME Types",
    description: "Pesquise tipos MIME por extensão de arquivo ou content-type",
    category: "Utilities",
    href: "/tools/mime",
    icon: "FileType",
    tags: ["mime", "content-type", "extensão", "arquivo", "tipo"],
  },
  {
    id: "qr-code",
    name: "Gerador QR Code",
    description: "Gere QR Code (PNG) para URLs e texto — tudo no browser",
    category: "Utilities",
    href: "/tools/qr-code",
    icon: "QrCode",
    tags: ["qr", "qrcode", "url", "png"],
    isNew: true,
    addedAt: "2026-05-15",
  },
  {
    id: "slug",
    name: "Slug / URL amigável",
    description: "Converta títulos em slugs para URLs, branches e ficheiros",
    category: "Utilities",
    href: "/tools/slug",
    icon: "Link2",
    tags: ["slug", "url", "seo", "branch"],
    isNew: true,
    addedAt: "2026-05-15",
  },
  {
    id: "semver",
    name: "Semver",
    description: "Compare versões semver e calcule bumps (patch / minor / major)",
    category: "Utilities",
    href: "/tools/semver",
    icon: "Package",
    tags: ["semver", "version", "npm", "release"],
    isNew: true,
    addedAt: "2026-05-15",
  },
  {
    id: "dns",
    name: "DNS Check",
    description: "Consulte registros DNS: A, AAAA, MX, TXT, NS, CNAME e mais",
    category: "Network",
    href: "/tools/dns",
    icon: "Globe",
    tags: ["dns", "domínio", "registros", "mx", "txt", "nameserver"],
  },
  {
    id: "headers",
    name: "HTTP Headers",
    description: "Inspecione os headers de resposta HTTP de qualquer URL",
    category: "Network",
    href: "/tools/headers",
    icon: "Server",
    tags: ["http", "headers", "cabeçalhos", "resposta", "url", "segurança"],
  },
  {
    id: "redirect-check",
    name: "Cadeia de redirects",
    description: "Siga redirecionamentos HTTP até ao destino (HEAD, limite de hops)",
    category: "Network",
    href: "/tools/redirect-check",
    icon: "Route",
    tags: ["redirect", "301", "302", "http", "url"],
    isNew: true,
    addedAt: "2026-05-15",
  },
  {
    id: "meta-preview",
    name: "Meta / Open Graph",
    description: "Pré-visualize título, descrição e og:image de uma página pública",
    category: "Network",
    href: "/tools/meta-preview",
    icon: "Tags",
    tags: ["open graph", "og", "meta", "seo", "preview"],
    isNew: true,
    addedAt: "2026-05-15",
  },
  {
    id: "cors-probe",
    name: "Sonda CORS",
    description: "Peça HEAD com Origin custom e veja cabeçalhos Access-Control-* devolvidos",
    category: "Network",
    href: "/tools/cors-probe",
    icon: "ShieldHalf",
    tags: ["cors", "origin", "http", "api"],
    isNew: true,
    addedAt: "2026-05-15",
  },
];

export const CATEGORIES = [
  ...new Set(TOOLS.map((t) => t.category)),
] as const;

export function getToolsByCategory(category: string) {
  return TOOLS.filter((t) => t.category === category);
}

export function searchTools(query: string) {
  const q = query.toLowerCase();
  return TOOLS.filter(
    (t) =>
      t.name.toLowerCase().includes(q) ||
      t.description.toLowerCase().includes(q) ||
      t.tags.some((tag) => tag.includes(q))
  );
}
