import type { Tool } from "@/types";

export const TOOLS: Tool[] = [
  {
    id: "json",
    name: "Formatador JSON",
    description: "Formate, valide, minifique e converta JSON para TypeScript",
    category: "JSON",
    href: "/tools/json",
    icon: "Braces",
    tags: ["json", "formatar", "validar", "typescript"],
    aliases: ["json formatter", "json format", "json prettify", "json minify"],
    privacy: "client-only",
    hasAI: true,
  },
  {
    id: "jsonpath",
    name: "JSONPath",
    description: "Filtre JSON com expressões JSONPath (no browser)",
    category: "JSON",
    href: "/tools/jsonpath",
    icon: "Filter",
    tags: ["jsonpath", "json", "query", "filtrar"],
    isNew: true,
    addedAt: "2026-05-15",
  },
  {
    id: "yaml",
    name: "YAML ↔ JSON",
    description: "Converta entre YAML e JSON para Kubernetes, CI/CD e configs",
    category: "JSON",
    href: "/tools/yaml",
    icon: "FileCode2",
    tags: ["yaml", "json", "kubernetes", "config", "converter"],
    isNew: true,
  },
  {
    id: "json-schema",
    name: "JSON Schema Validator",
    description: "Valide JSON contra um schema simples e gere erros legíveis",
    category: "JSON",
    href: "/tools/json-schema",
    icon: "Braces",
    tags: ["json schema", "schema", "validar", "api"],
    aliases: ["schema validator", "validate json schema", "ajv"],
    privacy: "client-only",
    isNew: true,
    addedAt: "2026-05-16",
  },
  {
    id: "openapi",
    name: "OpenAPI Viewer",
    description: "Resumo e validação rápida de specs OpenAPI/Swagger",
    category: "JSON",
    href: "/tools/openapi",
    icon: "FileCode2",
    tags: ["openapi", "swagger", "api", "schema"],
    aliases: ["swagger viewer", "openapi validator"],
    privacy: "client-only",
    isNew: true,
    addedAt: "2026-05-16",
  },
  {
    id: "rest-client",
    name: "REST Client",
    description: "Execute requests HTTP e salve coleções locais sem conta",
    category: "Network",
    href: "/tools/rest-client",
    icon: "Server",
    tags: ["rest", "api", "http", "client", "collection"],
    aliases: ["postman", "insomnia", "api client", "http client"],
    privacy: "server-api",
    isNew: true,
    addedAt: "2026-05-16",
  },
  {
    id: "curl-importer",
    name: "cURL Importer",
    description: "Converta cURL para request, fetch e HTTPie",
    category: "Network",
    href: "/tools/curl-importer",
    icon: "Terminal",
    tags: ["curl", "fetch", "axios", "httpie", "api"],
    aliases: ["curl to fetch", "curl parser"],
    privacy: "client-only",
    isNew: true,
    addedAt: "2026-05-16",
  },
  {
    id: "oauth-debugger",
    name: "OAuth/OIDC Debugger",
    description: "Gere PKCE, state e authorization URLs para OAuth/OIDC",
    category: "Security",
    href: "/tools/oauth-debugger",
    icon: "KeyRound",
    tags: ["oauth", "oidc", "pkce", "authorization", "login"],
    aliases: ["pkce generator", "oauth debugger", "oidc"],
    privacy: "client-only",
    isNew: true,
    addedAt: "2026-05-16",
  },
  {
    id: "regex",
    name: "Testador de Regex",
    description: "Teste expressões regulares com highlighting e explicação por IA",
    category: "Text",
    href: "/tools/regex",
    icon: "Regex",
    tags: ["regex", "regexp", "padrão", "expressão regular"],
    hasAI: true,
  },
  {
    id: "base64",
    name: "Codificador Base64",
    description: "Codifique e decodifique Base64, URL e entidades HTML",
    category: "Encoding",
    href: "/tools/base64",
    icon: "Binary",
    tags: ["base64", "codificar", "decodificar", "url", "html"],
    aliases: ["base64 decode", "base64 encode", "btoa", "atob"],
    privacy: "client-only",
  },
  {
    id: "jwt",
    name: "JWT — decodificar e gerar",
    description: "Decodifique tokens ou gere JWT HS256 para testes locais",
    category: "Security",
    href: "/tools/jwt",
    icon: "KeyRound",
    tags: ["jwt", "token", "auth", "decodificar", "hs256"],
    aliases: ["bearer", "access token", "id token", "jwt decode", "jwt sign", "jwks"],
    privacy: "client-only",
  },
  {
    id: "pem",
    name: "Visualizador PEM / certificado",
    description: "Cole PEM de certificado X.509 e veja subject, validade e fingerprints",
    category: "Security",
    href: "/tools/pem",
    icon: "FileKey",
    tags: ["pem", "x509", "certificado", "ssl", "tls"],
    isNew: true,
    addedAt: "2026-05-15",
  },
  {
    id: "jwk-pem",
    name: "JWK ↔ PEM",
    description: "Converta chaves públicas RSA entre JWK e PEM/SPKI",
    category: "Security",
    href: "/tools/jwk-pem",
    icon: "FileKey",
    tags: ["jwk", "pem", "rsa", "jwks", "chave"],
    aliases: ["jwk to pem", "pem to jwk", "jwks"],
    privacy: "client-only",
    isNew: true,
    addedAt: "2026-05-16",
  },
  {
    id: "csp",
    name: "CSP Builder / Analyzer",
    description: "Monte e analise Content-Security-Policy com avisos práticos",
    category: "Security",
    href: "/tools/csp",
    icon: "ShieldCheck",
    tags: ["csp", "security headers", "content security policy"],
    aliases: ["content-security-policy", "csp analyzer", "csp builder"],
    privacy: "client-only",
    isNew: true,
    addedAt: "2026-05-16",
  },
  {
    id: "secrets",
    name: "Gerador de Secrets",
    description: "Gere secrets aleatórios em base64 ou hex (openssl rand)",
    category: "Security",
    href: "/tools/secrets",
    icon: "Key",
    tags: ["secret", "openssl", "jwt", "webhook", "base64", "hex", "random"],
    isNew: true,
  },
  {
    id: "hash",
    name: "Gerador de Hash",
    description: "Digest MD5/SHA-2, HMAC para webhooks e comparação de hashes",
    category: "Security",
    href: "/tools/hash",
    icon: "Hash",
    tags: ["hash", "sha256", "sha384", "sha3", "blake2", "hmac", "md5", "webhook", "criptografia"],
  },
  {
    id: "estampas",
    name: "Estúdio de Estampas",
    description:
      "Prepare arte para camisetas: remover fundo (Rembg), DPI, knockout, presets DTF e camisa preta, export PNG/WebP",
    category: "Images",
    href: "/tools/estampas",
    icon: "Shirt",
    tags: ["estampa", "camiseta", "dtf", "sublimação", "knockout", "imagem", "rembg", "sharp"],
    isNew: true,
  },
  {
    id: "imagem-dev",
    name: "Imagem para dev",
    description: "Remova metadados EXIF e descarregue pack de favicons PNG (ZIP)",
    category: "Images",
    href: "/tools/imagem-dev",
    icon: "ImageDown",
    tags: ["imagem", "exif", "favicon", "png", "zip"],
    isNew: true,
    addedAt: "2026-05-15",
  },
  {
    id: "colors",
    name: "Conversor de Cores",
    description: "Converta entre HEX, RGB, HSL, HSV e CMYK com preview",
    category: "Colors",
    href: "/tools/colors",
    icon: "Palette",
    tags: ["cor", "hex", "rgb", "hsl", "css"],
  },
  {
    id: "password",
    name: "Gerador de Senha",
    description: "Gere senhas seguras com regras customizáveis e análise de força",
    category: "Security",
    href: "/tools/password",
    icon: "ShieldCheck",
    tags: ["senha", "segurança", "gerador", "aleatório"],
  },
  {
    id: "uuid",
    name: "Gerador de UUID",
    description: "Gere UUIDs v4 criptograficamente seguros em massa",
    category: "Utilities",
    href: "/tools/uuid",
    icon: "Fingerprint",
    tags: ["uuid", "guid", "id", "único"],
    aliases: ["uuid v7", "ulid", "nanoid", "random id"],
    privacy: "client-only",
  },
  {
    id: "diff",
    name: "Comparador de Texto",
    description: "Compare dois textos e visualize as diferenças com highlighting",
    category: "Text",
    href: "/tools/diff",
    icon: "GitCompare",
    tags: ["diff", "comparar", "texto", "diferenças"],
  },
  {
    id: "markdown",
    name: "Preview Markdown",
    description: "Escreva Markdown e veja o preview renderizado em tempo real",
    category: "Text",
    href: "/tools/markdown",
    icon: "FileText",
    tags: ["markdown", "md", "preview", "renderizar"],
  },
  {
    id: "lorem",
    name: "Lorem & dados fictícios",
    description: "Gere texto e dados de teste com seed reproduzível (Faker)",
    category: "Text",
    href: "/tools/lorem",
    icon: "Library",
    tags: ["lorem", "faker", "dados", "teste", "seed"],
    isNew: true,
    addedAt: "2026-05-15",
  },
  {
    id: "code-review",
    name: "Revisão de Código IA",
    description: "Revise seu código com IA: bugs, performance e boas práticas",
    category: "Code",
    href: "/tools/code-review",
    icon: "Bot",
    tags: ["ia", "código", "revisão", "refatorar"],
    hasAI: true,
  },
  {
    id: "sql",
    name: "Formatador SQL",
    description: "Formate queries SQL e obtenha explicações por IA",
    category: "Database",
    href: "/tools/sql",
    icon: "Database",
    tags: ["sql", "banco de dados", "query", "formatar"],
    hasAI: true,
  },
  {
    id: "env",
    name: "Env Toolkit",
    description: "Valide, compare, ordene e mascare variáveis de ambiente",
    category: "Utilities",
    href: "/tools/env",
    icon: "Variable",
    tags: ["env", "dotenv", "variáveis", "ambiente", "secrets"],
    isNew: true,
  },
  {
    id: "ignore-generator",
    name: "Ignore Generator",
    description: "Gere .gitignore, .dockerignore e .npmignore por stack",
    category: "Utilities",
    href: "/tools/ignore-generator",
    icon: "FileText",
    tags: ["gitignore", "dockerignore", "npmignore", "ignore"],
    aliases: ["ignore files", ".gitignore generator"],
    privacy: "client-only",
    isNew: true,
    addedAt: "2026-05-16",
  },
  {
    id: "logs",
    name: "Logs Toolkit",
    description: "Formate JSON/NDJSON, filtre logs e destaque níveis",
    category: "Text",
    href: "/tools/logs",
    icon: "FileText",
    tags: ["logs", "jsonl", "ndjson", "debug", "observability"],
    aliases: ["log formatter", "json logs"],
    privacy: "client-only",
    isNew: true,
    addedAt: "2026-05-16",
  },
  {
    id: "web-standards",
    name: "Web Standards Generator",
    description: "Gere robots.txt, sitemap.xml, security.txt e headers",
    category: "Network",
    href: "/tools/web-standards",
    icon: "FileText",
    tags: ["robots", "sitemap", "security.txt", "headers", "seo"],
    aliases: ["robots generator", "sitemap generator", "security txt"],
    privacy: "client-only",
    isNew: true,
    addedAt: "2026-05-16",
  },
  {
    id: "explain-error",
    name: "Explique esse erro",
    description: "Diagnostique stack traces, logs e erros de build com IA opt-in",
    category: "Code",
    href: "/tools/explain-error",
    icon: "Bot",
    tags: ["erro", "stack trace", "debug", "ia"],
    aliases: ["explain error", "debug error", "stack trace ai"],
    privacy: "ai-assisted",
    hasAI: true,
    isNew: true,
    addedAt: "2026-05-16",
  },
  {
    id: "schema-from-examples",
    name: "Schema From Examples",
    description: "Gere JSON Schema, TypeScript e Zod a partir de exemplos",
    category: "JSON",
    href: "/tools/schema-from-examples",
    icon: "Braces",
    tags: ["schema", "json", "typescript", "zod", "infer"],
    aliases: ["infer schema", "json to schema", "schema generator"],
    privacy: "client-only",
    isNew: true,
    addedAt: "2026-05-16",
  },
  {
    id: "test-generator",
    name: "Test Generator",
    description: "Gere esqueleto de testes e sugestões com IA opt-in",
    category: "Code",
    href: "/tools/test-generator",
    icon: "Bot",
    tags: ["testes", "vitest", "jest", "playwright", "ia"],
    aliases: ["test generator", "generate tests", "unit tests"],
    privacy: "ai-assisted",
    hasAI: true,
    isNew: true,
    addedAt: "2026-05-16",
  },
  {
    id: "deploy-checklist",
    name: "Deploy Checklist",
    description: "Agregue checks de status, SSL, headers, robots, CORS e redirects",
    category: "Network",
    href: "/tools/deploy-checklist",
    icon: "ShieldCheck",
    tags: ["deploy", "checklist", "ssl", "headers", "cors", "robots"],
    aliases: ["production checklist", "launch checklist", "deployment"],
    privacy: "ai-assisted",
    hasAI: true,
    isNew: true,
    addedAt: "2026-05-16",
  },
  {
    id: "base-converter",
    name: "Conversor de bases",
    description: "Converta entre binário, octal, decimal e hexadecimal",
    category: "Utilities",
    href: "/tools/base-converter",
    icon: "Calculator",
    tags: ["binário", "hex", "decimal", "octal", "base", "número"],
    isNew: true,
  },
  {
    id: "cron",
    name: "Interpretador Cron",
    description: "Interprete e gere expressões cron com descrição em português",
    category: "Utilities",
    href: "/tools/cron",
    icon: "Clock",
    tags: ["cron", "agendamento", "tempo", "job"],
    aliases: ["crontab", "scheduler", "next runs", "próximas execuções"],
    privacy: "client-only",
  },
  {
    id: "timestamp",
    name: "Conversor de Timestamp",
    description: "Converta timestamps Unix para datas legíveis e vice-versa",
    category: "Utilities",
    href: "/tools/timestamp",
    icon: "Timer",
    tags: ["timestamp", "unix", "data", "tempo", "converter"],
  },
  {
    id: "calculadora-datas",
    name: "Calculadora de Datas",
    description: "Some dias, semanas, meses e anos; calcule diferenças e prazos em formato brasileiro",
    category: "Utilities",
    href: "/tools/calculadora-datas",
    icon: "CalendarDays",
    tags: ["data", "datas", "dias", "calendário", "prazo", "idade", "diferença", "brasil"],
    aliases: ["contador de dias", "calcular dias", "dias entre datas", "date calculator", "prazo"],
    privacy: "client-only",
    isNew: true,
    addedAt: "2026-05-16",
  },
  {
    id: "zod-schema",
    name: "Zod / TypeScript / Schema",
    description: "Conversões rápidas entre JSON Schema, TypeScript e esboços Zod",
    category: "Utilities",
    href: "/tools/zod-schema",
    icon: "FileCode2",
    tags: ["zod", "typescript", "json schema", "converter"],
    aliases: ["zod to json schema", "typescript to schema", "schema to typescript"],
    privacy: "client-only",
    isNew: true,
    addedAt: "2026-05-16",
  },
  {
    id: "mime",
    name: "MIME Types",
    description: "Pesquise tipos MIME por extensão de arquivo ou content-type",
    category: "Utilities",
    href: "/tools/mime",
    icon: "FileType",
    tags: ["mime", "content-type", "extensão", "arquivo", "tipo"],
  },
  {
    id: "qr-code",
    name: "Gerador QR Code",
    description: "Gere QR Code (PNG) para URLs e texto — tudo no browser",
    category: "Utilities",
    href: "/tools/qr-code",
    icon: "QrCode",
    tags: ["qr", "qrcode", "url", "png"],
    isNew: true,
    addedAt: "2026-05-15",
  },
  {
    id: "slug",
    name: "Slug / URL amigável",
    description: "Converta títulos em slugs para URLs, branches e ficheiros",
    category: "Utilities",
    href: "/tools/slug",
    icon: "Link2",
    tags: ["slug", "url", "seo", "branch"],
    isNew: true,
    addedAt: "2026-05-15",
  },
  {
    id: "semver",
    name: "Semver",
    description: "Compare versões semver e calcule bumps (patch / minor / major)",
    category: "Utilities",
    href: "/tools/semver",
    icon: "Package",
    tags: ["semver", "version", "npm", "release"],
    isNew: true,
    addedAt: "2026-05-15",
  },
  {
    id: "dns",
    name: "DNS Check",
    description: "Consulte registros DNS: A, AAAA, MX, TXT, NS, CNAME e mais",
    category: "Network",
    href: "/tools/dns",
    icon: "Globe",
    tags: ["dns", "domínio", "registros", "mx", "txt", "nameserver"],
    aliases: ["dns all", "todos dns", "lookup", "dig", "nslookup"],
    privacy: "server-api",
  },
  {
    id: "headers",
    name: "HTTP Headers",
    description: "Inspecione os headers de resposta HTTP de qualquer URL",
    category: "Network",
    href: "/tools/headers",
    icon: "Server",
    tags: ["http", "headers", "cabeçalhos", "resposta", "url", "segurança"],
    aliases: ["header checker", "http headers", "security headers"],
    privacy: "server-api",
  },
  {
    id: "robots-sitemap",
    name: "Robots/Sitemap Validator",
    description: "Verifique robots.txt e sitemap.xml de um domínio público",
    category: "Network",
    href: "/tools/robots-sitemap",
    icon: "FileText",
    tags: ["robots", "sitemap", "seo", "crawler"],
    aliases: ["robots.txt", "sitemap.xml", "seo validator"],
    privacy: "server-api",
    isNew: true,
    addedAt: "2026-05-16",
  },
  {
    id: "ssl-check",
    name: "SSL/TLS Checker",
    description: "Inspecione certificado TLS, emissor, validade e protocolo",
    category: "Network",
    href: "/tools/ssl-check",
    icon: "ShieldCheck",
    tags: ["ssl", "tls", "certificado", "https"],
    aliases: ["certificate checker", "tls checker", "ssl cert"],
    privacy: "server-api",
    isNew: true,
    addedAt: "2026-05-16",
  },
  {
    id: "http-status",
    name: "HTTP Status / Latency",
    description: "Cheque status HTTP, latência, URL final e headers principais",
    category: "Network",
    href: "/tools/http-status",
    icon: "Server",
    tags: ["http", "status", "latency", "uptime", "api"],
    aliases: ["status checker", "latency check", "api health"],
    privacy: "server-api",
    isNew: true,
    addedAt: "2026-05-16",
  },
  {
    id: "webhook-mock",
    name: "Webhook Mock",
    description: "Gere payloads, cURL e teste echo para webhooks",
    category: "Network",
    href: "/tools/webhook-mock",
    icon: "Server",
    tags: ["webhook", "mock", "curl", "payload"],
    aliases: ["webhook inspector", "webhook test", "request bin"],
    privacy: "server-api",
    isNew: true,
    addedAt: "2026-05-16",
  },
  {
    id: "redirect-check",
    name: "Cadeia de redirects",
    description: "Siga redirecionamentos HTTP até ao destino (HEAD, limite de hops)",
    category: "Network",
    href: "/tools/redirect-check",
    icon: "Route",
    tags: ["redirect", "301", "302", "http", "url"],
    aliases: ["redirect chain", "url redirect", "301 302"],
    privacy: "server-api",
    isNew: true,
    addedAt: "2026-05-15",
  },
  {
    id: "meta-preview",
    name: "Meta / Open Graph",
    description: "Pré-visualize título, descrição e og:image de uma página pública",
    category: "Network",
    href: "/tools/meta-preview",
    icon: "Tags",
    tags: ["open graph", "og", "meta", "seo", "preview"],
    aliases: ["og preview", "social preview", "meta tags"],
    privacy: "server-api",
    isNew: true,
    addedAt: "2026-05-15",
  },
  {
    id: "cors-probe",
    name: "Sonda CORS",
    description: "Peça HEAD com Origin custom e veja cabeçalhos Access-Control-* devolvidos",
    category: "Network",
    href: "/tools/cors-probe",
    icon: "ShieldHalf",
    tags: ["cors", "origin", "http", "api"],
    aliases: ["cors checker", "access-control-allow-origin", "preflight"],
    privacy: "server-api",
    isNew: true,
    addedAt: "2026-05-15",
  },
];

export const TOOL_COLLECTIONS = [
  {
    id: "api-debug",
    name: "API Debug Platform",
    description: "REST Client, cURL, OpenAPI, rede, headers, CORS, redirects e deploy checks.",
    toolIds: ["rest-client", "curl-importer", "openapi", "oauth-debugger", "http-status", "headers", "cors-probe", "redirect-check", "dns", "ssl-check", "robots-sitemap", "webhook-mock", "meta-preview", "deploy-checklist", "jwt"],
  },
  {
    id: "frontend",
    name: "Frontend",
    description: "Cores, imagens, QR Code, meta tags e utilidades de UI.",
    toolIds: ["colors", "imagem-dev", "qr-code", "meta-preview", "markdown", "slug"],
  },
  {
    id: "security",
    name: "Segurança",
    description: "JWT, certificados, secrets, senhas, hashes e headers.",
    toolIds: ["jwt", "jwk-pem", "pem", "csp", "secrets", "password", "hash", "headers", "ssl-check"],
  },
  {
    id: "images",
    name: "Imagens",
    description: "Estampas, metadados, favicons e exportações.",
    toolIds: ["estampas", "imagem-dev", "colors", "qr-code"],
  },
  {
    id: "json-api",
    name: "JSON/API",
    description: "JSON, YAML, JSONPath, Base64, timestamps e dados fake.",
    toolIds: ["json", "json-schema", "schema-from-examples", "openapi", "zod-schema", "yaml", "jsonpath", "base64", "timestamp", "lorem"],
  },
  {
    id: "daily-dev",
    name: "Daily Dev",
    description: "Ferramentas rápidas para arquivos, logs, env e padrões web.",
    toolIds: ["env", "ignore-generator", "logs", "web-standards", "slug", "semver", "cron", "timestamp"],
  },
  {
    id: "ai-assistants",
    name: "AI Assistants",
    description: "Assistentes opt-in para debug, testes e deploy.",
    toolIds: ["explain-error", "test-generator", "deploy-checklist", "code-review", "json", "regex", "sql"],
  },
] as const;

export const CATEGORIES = [
  ...new Set(TOOLS.map((t) => t.category)),
] as const;

export function getToolsByCategory(category: string) {
  return TOOLS.filter((t) => t.category === category);
}

export function searchTools(query: string) {
  const q = query.toLowerCase();
  return TOOLS.filter(
    (t) =>
      t.name.toLowerCase().includes(q) ||
      t.description.toLowerCase().includes(q) ||
      t.tags.some((tag) => tag.toLowerCase().includes(q)) ||
      (t.aliases ?? []).some((alias) => alias.toLowerCase().includes(q))
  );
}
